### ISSUE TITLE
역할 분담

### ISSUE THREAD

**Issue by CourtneyCho** [taeyang1224/Team-practice#1]
역할 분담을 어떻게 할까요?

**Comment by dongyoung0** [comment]
조장님 프로젝트 관리
introduce.md 작성 - 2명
fizzbuzz.py 작성 - 1명
이렇게 나눠야 할까요?

**Comment by taeyang1224** [comment]
처음엔 각자 소개를 나눠볼까 했는데 그렇게 하면 좋을 것 같아요 !

**Comment by dongyoung0** [comment]
혹시 그럼 제가 fizzbuzz.py 파일 작성해도 될까요?

**Comment by CourtneyCho** [comment]
네^^ 그럼 introduce에는 제 소개만 써야되는 건가요?

**Comment by taeyang1224** [comment]
그러면 동영님이 코드 맡아 주시고 지민님이랑 구미님이 소개하는거로 할까요?

**Comment by CourtneyCho** [comment]
네! 그럼 소개는 팀을 소개하는 내용을 적어야 되는 건가요?

**Comment by taeyang1224** [comment]
네 그런것 같습니다 ! 제가 이슈 달아드릴게요 !

**Comment by whynotg** [comment]
컴퓨터 재부팅 하고 오느라 늦었습니다 내용 확인 했어요!

**Comment by CourtneyCho** [comment]
네^^ 그럼 구미님이랑 저랑 적을 내용을 나눌까요?

**Comment by whynotg** [comment]
네, 여기서 각자 맡을 내용 나누고 각자 이슈 작성하면 될것 같아요. 우선 각자 본인 소개하고 팀장님, 동영님 소개 추가로 하나씩 더 작성하면 될까요?

**Comment by CourtneyCho** [comment]
네~ 그럼 제가 팀장님 소개랑 제 소개 적을게요~

**Comment by taeyang1224** [comment]
큰 틀은 제가 이슈로 남겨드렸습니다 !

**Comment by whynotg** [comment]
감사합니다, 그럼 제가 저랑 동영님 소개 적을게요. 혹시 동영님 이름, 깃허브 아이디 외에 넣고 싶으신 내용이나 문구 있으시면 남겨주세요~
